# vi: set ft=ruby :

provision_a =<<EOF
apt-get update
apt-get -y install nginx
EOF

provision_b =<<EOF
mv /tmp/nginx.conf /etc/nginx/sites-available/default
/etc/init.d/nginx reload
EOF

Vagrant.configure('2') do |config|
  # Host name of the VM
  config.vm.hostname = "cache.example.com"

  # Base image for VM
  config.vm.box = "ubuntu/trusty64"

  # Configure private network by DHCP
  config.vm.network "private_network", type: "dhcp"

  # Update /etc/hosts on all active VMs
  config.hostmanager.enabled = true

  # Update host machine's /etc/hosts
  config.hostmanager.manage_host = true

  # Don't ignore private IPs
  config.hostmanager.ignore_private_ip = false

  # Include offline VMs (rather than just active ones)
  config.hostmanager.include_offline = true

  # Use IP resolver to get DHCP configured address
  config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
    `vagrant ssh -c "hostname -I"`.split.last
  end

  # Aliases
  config.hostmanager.aliases = %w(cache1.example.com cache2.example.com)

  # Provisioning (part A)
  config.vm.provision "shell", privileged: true, inline: provision_a

  # Copy nginx config to a temporary location to be picked up by shell script B
  config.vm.provision "file", source: "nginx.conf", destination: "/tmp/nginx.conf"

  # Provisioning (part B)
  config.vm.provision "shell", privileged: true, inline: provision_b
end
