#! /bin/bash
set -e

# compute main stack directory based on the location of this script
MY_DIR="$(cd "$(dirname "$0")" && pwd)"

# flag of last successful update
MY_FLAG="$MY_DIR/.last-update"

# optional parameter indicating minimum update interval in find-compatible time
# (i.e. do not update unless it has been X time since last update)
if [ -n "$1" ]; then
    # minimum interval was specified
    MY_INTERVAL="$1"
    
    # see if flag file exists within that interval
    MY_COUNT=`find "$MY_FLAG" -mtime -$MY_INTERVAL -depth 0 | wc -l`

    if [ $MY_COUNT -gt 0 ]; then
        echo "=> Skipping update"
        exit
    else
        echo "=> Missing or outdated flag $MY_FLAG" 
    fi
fi

cd "$MY_DIR"

echo "=> Updating from git..." 
git pull

echo "=> Re-installing..." 
./install

# update flag
touch "$MY_FLAG"
