#!/bin/bash

################################################################################
## FILE HELPERS ################################################################
################################################################################

# detailed file list
alias ll='ls -lah'

# show details of a file (including access rights in octal)
alias d='stat -c "%A (%a) %8s %.19y %n"'

# rsync -a archive, -v verbose, -z compressed, -h human, -P progress and partial
alias rcopy='rsync -avzhP'

# with --delete (delete extraneous files from dest dirs BEFORE transfer)
alias rcopyd='rsync -avzhP --delete'

# extracts a zipped tar file
alias untar='tar xvzf'

# reverse lines in file
alias reverse-file="awk '{ a[NR]=\$0 } END { for(i=NR; i; --i) print a[i] }'"

# count files in all subdirectories
alias count-files="find . -type f | wc -l"

################################################################################
## CODING ######################################################################
################################################################################

# revision control shortcuts
alias g='git-auto'
alias st="svn --ignore-externals status"
alias sc="svn commit"
alias sl="svn log | less"
alias sup="svn up --ignore-externals"
alias svd="svn diff | colordiff | less -R"
alias svn-add-all="svn status | awk '{if (\$1 == \"?\") print \$2 }' | xargs svn add"
alias svn-del-all="svn status | awk '{if (\$1 == \"!\") print \$2 }' | xargs svn delete"

# debugging SSL
# e.g. show-certs smtpout.secureserver.net:465
alias show-certs='openssl s_client -showcerts -connect'
# e.g. msmtp-certs --host=smtpout.secureserver.net 
alias msmtp-certs='msmtp --tls-certcheck=off --tls=on --tls-starttls=off --port=465 --serverinfo'

# tidy up xml/html e.g. tidy-xml file.html
alias tidy-xml='tidy -i -xml'

# tunnel MySQL on port 9999
alias mysql-tunnel='ssh -L 9999:127.0.0.1:3306'

# spider a site
#
# -nc             Normally new copies of files are downloaded, but here the original 
#                 version is preserved and any newer copies on the server to be ignored.
#                 Files with the suffixes .html or .htm will be loaded from the local
#                 disk and parsed as if they had been retrieved from the Web.
#
# -nv             Turn off verbose without being completely quiet (use -q for that), which
#                 means that error messages and basic information still get printed.
#
# -r              Turn on recursive retrieving.
#
# --random-wait   Vary wait time between requests between 0.5 and 1.5 seconds.
#
# --wait=seconds  Wait the specified number of seconds between the retrievals.  
#
# -l depth        Specify recursion maximum depth level depth. Default is 5.
#
# -R              Specify comma-separated lists of file name suffixes or patterns to reject.
#
# -np             Do not ever ascend to the parent directory when retrieving recursively.
#                 This is a useful option, since it guarantees that only the files below a
#                 certain hierarchy will be downloaded.
#
alias spider='wget -nc -nv -r --random-wait --wait=1 -l9 -np'
alias spider-html='wget -nc -nv -r --random-wait --wait=1 -l9 -R .jpg,.JPG,.gif,.GIF,.png,.PNG -np'

# watch particular vhost log files
alias tail-vhost-access='sudo tail -f /var/log/apache2/vhost-access.log'
alias tail-vhost-error='sudo tail -f /var/log/apache2/vhost-error.log'

# note taking
alias n="note"
alias ng="note | grep"

# add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# find in files
alias ff='ack-grep'

################################################################################
## SECURITY ####################################################################
################################################################################

# generate passwords
alias pw-secure='pwgen --secure 32 1'
alias pw-symbols='pwgen --secure --symbols 32 1'
alias pw-numbers='ruby -e "puts rand(2 ** 100)"'

# encryption
# e.g.
# encrypt-salted in.key | xxd
# unhex-typed typed.hex | decrypt-stream > out.key
alias encrypt-salted='openssl aes-256-cbc -salt -in'
alias unhex-typed='xxd -r -p'
alias decrypt-stream='openssl aes-256-cbc -d'

################################################################################
## UBUNTU ######################################################################
################################################################################

# open in new tab in existing gvim
alias e="gvim --remote-tab"

# find matching packages
alias apt-find='apt-cache search'

# memorable synonym for a useful program
alias usage='baobab'

# install headers for the current kernel
alias apt-install-kernel-headers='sudo apt-get install linux-headers-`uname -r`'

# update and upgrade in one command
alias upgrade='sudo sh -c "apt-get update && apt-get upgrade"'

################################################################################
## DEVICES #####################################################################
################################################################################

# show info on connected SATA drives
alias sd='dmesg | grep "\[sd.\]"'

# show hard-drive temperatures for /dev/sda and /dev/sdb
alias temp='sudo hddtemp /dev/sda && sudo hddtemp /dev/sdb'

# show battery information
alias batt="acpi | awk '{ print \$4 \$5 }' | sed 's/,/ /'"

################################################################################
## FUN #########################################################################
################################################################################

# sounds
alias sound-toot='play -n synth 0.3 sine 300-3300 vol 0.1 &> /dev/null'
alias sound-alarm='play -n synth 2 sine 300-3000 sine 3000-300 repeat 20 vol 0.1 &> /dev/null'
