" load pathogen bundles
" @see https://github.com/tpope/vim-pathogen
runtime bundle/pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

runtime autoload/util.vim

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" GENERAL PREFERENCES
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" we're running Vim, not Vi!
set nocompatible          

" enable syntax highlighting
syntax on

" enable filetype-specific indenting and plugins
filetype plugin indent on

" show line numbers
set number

" set colour scheme
colorscheme slate-variant

" automatically reload vimrc upon save
au! BufWritePost .vimrc source %

" ignore certain extensions and locations (affects Command-T)
set wildignore+=.svn,.git
set wildignore+=www/app/cache/**,www/web/bundles/**,www/sites/default/files/**,www/backup/**
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg,*.JPG,*.BMP,*.GIF,*.PNG,*.JPEG

" autocomplete: pick longest match first, then cycle through list
set wildmode=longest,list,full

" no toolbar, menu, or right scroll bar (in gvim)
set guioptions-=T
set guioptions-=m
set guioptions-=r

" prevent overflowing output when doing find-in-files
set nomore	

" show matching parenteses
set noshowmatch

" incremental search
set incsearch	

" highlight search result
set hlsearch

" case insensitive search
set noignorecase

" back to case sensitive for searches containing UPPERCASE
set nosmartcase

" automatically scroll so that at least this lines are above or below cursor
set scrolloff=5 

" use spaces instead of tabs
set expandtab

" start new line at appropriate indentation level
set smartindent

" make tab bar always visible (to prevent annoying appearing/disappearing)
set showtabline=2

" shorten waiting for mapping disambiguation
set timeoutlen=200

" wrap words visually
set lbr 

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" PLUGIN CONFIGURATION
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" allow 50K files to show up in Command-T
let g:CommandTMaxFiles=50000
" show the best match at the bottom of the Command-T window.
let g:CommandTMatchWindowReverse = 1 
" open Command-T files in a new tab by default
let g:CommandTAcceptSelectionTabMap='<CR>'
" use Ctrl+O to open file in the current tab
let g:CommandTAcceptSelectionMap='<C-o>' 

"au BufRead,BufNewFile *.twig set syntax=htmljinja
autocmd BufReadPost * :DetectIndent

" disable syntax checking on twig files -- it does not seem to work
let g:syntastic_mode_map = { 'mode' : 'active', 'active_filetypes' : [], 'passive_filetypes': ['twig'] }

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"" KEYBOARD 
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" map leader and often-used shortcuts
let mapleader=","
map <leader>t :call util#BeginCommandT()<CR>
map <leader>g :CommandTFlush<CR>:call util#BeginCommandT()<CR>
map <leader>a :Align 
map <Leader>r :UtilPowerReplace 
map <Leader>q :UtilQuickfixToArgs<CR>
map <Leader>f :Ack --ignore-dir=cache --ignore-dir=vendor --ignore-dir=web -i 
map <Leader>n :wincmd w<CR>

" use Ctrl+k and Ctrl+j to switch between open tabs
map <C-k> gT
map <C-j> gt
map <C-w> :tabclose<CR>

" use Ctrl+n to hop to next quickfix item
map <C-n> :w<CR>:cn<CR>

" write to file
map <Leader><Leader> :w<CR>

" cut, copy, paste
map <Leader>x "+x
map <Leader>c "+y
map <Leader>v "+gP

" delete without destroying buffer
map <Leader>d "_d

" switch to usual indents
map <Leader>4 :set tabstop=4 softtabstop=4 shiftwidth=4 expandtab<CR>
map <Leader>2 :set tabstop=2 softtabstop=2 shiftwidth=2 expandtab<CR>

" pull full path name into paste buffer for attachment to email etc
nnoremap <Leader>p :let @*=expand("%")<CR>
"nnoremap <F2> :let @*=substitute(expand("%:p"), "/", "\\", "g")<cr>

" use Tab to initiate autocomplete
imap <Tab> <C-n>
