#!/bin/bash
 
# use capslock key as super
setxkbmap -option caps:super

# oldschool gray background
xsetroot -gray

# load profile stuff
if [ -f $HOME/.profile ]; then
    . $HOME/.profile
fi 

exec xmonad
