#!/usr/bin/env node
var path = require('path');
var parameters = process.argv.slice(2);
var script = path.basename(process.argv[1]);

// Require at least one parameter
if (parameters.length == 0) {
  console.log("Usage: " + script + " param");
  process.exit(1);
}

var fileName = parameters[0];
console.log("You entered: " + fileName);
